device: 'cuda'
model_kwargs:
  pick_models_kwargs:
    - configs_root_dir: 'configs/sapien/pick_lowres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'example_runs/2023_07_27_22-44-22_Pick_LowRes_Sapien_5_mug/checkpoint/200.pt'
      n_warmups: 10
    - configs_root_dir: 'configs/sapien/pick_highres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'example_runs/2023_07_27_22-58-39_Pick_HiRes_Sapien_5_mug/checkpoint/200.pt'
      n_warmups: 10
  place_models_kwargs:
    - configs_root_dir: 'configs/sapien/place_lowres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'example_runs/2023_07_27_23-06-52_Place_LowRes_Sapien_5_mug/checkpoint/200.pt'
      n_warmups: 10
    - configs_root_dir: 'configs/sapien/place_highres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'example_runs/2023_07_27_23-33-08_Place_HiRes_Sapien_5_mug/checkpoint/200.pt'
      n_warmups: 10