device: 'cuda'
model_kwargs:
  pick_models_kwargs:
    - configs_root_dir: 'configs/panda_mug/pick_lowres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'runs/2023_09_23_13-49-33_Pick_LowRes_Panda/checkpoint/180.pt'
      n_warmups: 10
    - configs_root_dir: 'configs/panda_mug/pick_highres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'runs/2023_09_23_14-00-27_Pick_HiRes_Panda/checkpoint/180.pt'
      n_warmups: 10
  pick_critic_kwargs:
    configs_root_dir: 'configs/panda_mug/ebm'
    train_configs_file: 'train_configs.yaml'
    task_configs_file: 'task_configs.yaml'
    checkpoint_dir: 'runs/2023_09_27_18-47-29_EBM_Panda/checkpoint/180.pt'
    n_warmups: 10
  place_models_kwargs:
    - configs_root_dir: 'configs/panda_mug/place_lowres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'runs/2023_10_03_20-48-38_Place_LowRes_Panda/checkpoint/200.pt'
      n_warmups: 10
    - configs_root_dir: 'configs/panda_mug/place_highres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'runs/2023_10_03_21-07-49_Place_HiRes_Panda/checkpoint/200.pt'
      n_warmups: 10
  place_critic_kwargs:
    configs_root_dir: 'configs/panda_mug/place_ebm'
    train_configs_file: 'train_configs.yaml'
    task_configs_file: 'task_configs.yaml'
    checkpoint_dir: 'runs/2023_10_03_21-28-18_Place_EBM_Panda/checkpoint/200.pt'
    n_warmups: 10