device: 'cuda'
model_kwargs:
  pick_models_kwargs:
    - configs_root_dir: 'configs/sapien/pick_lowres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'runs/2023_07_29_23-02-50_Pick_LowRes_Sapien_5_bottle/checkpoint/200.pt'
      n_warmups: 10
    - configs_root_dir: 'configs/sapien/pick_highres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'runs/2023_07_29_23-13-35_Pick_HiRes_Sapien_5_bottle/checkpoint/200.pt'
      n_warmups: 10
  place_models_kwargs:
    - configs_root_dir: 'configs/sapien/place_lowres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'runs/2023_07_29_22-28-43_Place_LowRes_Sapien_5_bottle/checkpoint/200.pt'
      n_warmups: 10
    - configs_root_dir: 'configs/sapien/place_highres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'runs/2023_07_29_22-51-21_Place_HiRes_Sapien_5_bottle/checkpoint/200.pt'
      n_warmups: 10