device: 'cuda'
model_kwargs:
  pick_models_kwargs:
    - configs_root_dir: 'configs/sapien/pick_lowres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'checkpoints/sim_bottle/pick_lo_200.pt'
      n_warmups: 10
    - configs_root_dir: 'configs/sapien/pick_highres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'checkpoints/sim_bottle/pick_hi_200.pt'
      n_warmups: 10
  place_models_kwargs:
    - configs_root_dir: 'configs/sapien/place_lowres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'checkpoints/sim_bottle/place_lo_200.pt'
      n_warmups: 10
    - configs_root_dir: 'configs/sapien/place_highres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'checkpoints/sim_bottle/place_hi_200.pt'
      n_warmups: 10