device: 'cuda'
model_kwargs:
  pick_models_kwargs:
    - configs_root_dir: 'configs/pick_lowres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'example_runs/2023_06_10_19-03-02_Pick_LowRes/checkpoint/200.pt'
      n_warmups: 10
    - configs_root_dir: 'configs/pick_highres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'example_runs/2023_06_10_20-43-44_Pick_HiRes/checkpoint/200.pt'
      n_warmups: 10
  place_models_kwargs:
    - configs_root_dir: 'configs/place_lowres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'example_runs/2023_06_10_19-28-19_Place_LowRes/checkpoint/200.pt'
      n_warmups: 10
    - configs_root_dir: 'configs/place_highres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'example_runs/2023_06_10_19-47-02_Place_HiRes/checkpoint/200.pt'
      n_warmups: 10