pick_diffusion_configs:
  N_steps_list: [[200, 200], [200, 200, 100]]
  timesteps_list: [[0.04, 0.04], [0.02, 0.02, 0.01]]
  temperatures_list: [[1., 1.], [1., 1., 0.0]]
  diffusion_schedules_list:
    - [[1., 0.15], [0.15, 0.09]]
    - [[0.09, 0.03], [0.03, 0.012], [0.012, 0.012]]
  time_exponent_temp: 1.0
  time_exponent_alpha: 0.5
  log_t_schedule: True
pick_trajectory_configs:
  approach_len: 0.1
  n_steps: 10
place_diffusion_configs:
  N_steps_list: [[200, 200], [200, 200, 100]]
  timesteps_list: [[0.04, 0.04], [0.02, 0.02, 0.01]]
  temperatures_list: [[1., 1.], [1., 1., 0.0]]
  diffusion_schedules_list:
    - [[1., 0.15], [0.15, 0.09]]
    - [[0.09, 0.03], [0.03, 0.012], [0.012, 0.012]]
  time_exponent_temp: 1.0
  time_exponent_alpha: 0.5
  log_t_schedule: True
place_trajectory_configs:
  n_steps: 20
  dt: 0.0001
  cutoff_r: 0.05
  max_num_neighbors: 100
  eps: 0.0001
  cluster_method: 'knn'
  voxel_size: 0.01
  voxel_coord_reduction: 'average'



