device: 'cuda'
model_kwargs:
  pick_models_kwargs:
    - configs_root_dir: 'configs/real_robot_mug/pick_lowres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'runs/2023_09_12_17-14-20_Pick_LowRes_Real_Mug/checkpoint/200.pt'
      n_warmups: 10
    - configs_root_dir: 'configs/real_robot_mug/pick_highres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: 'runs/2023_09_12_17-29-49_Pick_HiRes_Real_Mug/checkpoint/200.pt'
      n_warmups: 10
  place_models_kwargs: []
    # - configs_root_dir: 'configs/sapien/place_lowres'
    #   train_configs_file: 'train_configs.yaml'
    #   task_configs_file: 'task_configs.yaml'
    #   checkpoint_dir: 'example_runs/2023_07_27_23-06-52_Place_LowRes_Sapien_5_mug/checkpoint/200.pt'
    #   n_warmups: 10
    # - configs_root_dir: 'configs/sapien/place_highres'
    #   train_configs_file: 'train_configs.yaml'
    #   task_configs_file: 'task_configs.yaml'
    #   checkpoint_dir: 'example_runs/2023_07_27_23-33-08_Place_HiRes_Sapien_5_mug/checkpoint/200.pt'
    #   n_warmups: 10